### ISSUE TITLE
Kinetic shape_tools

### ISSUE THREAD

**Issue by nikkk91** [JenniferBuehler/moveit-pkgs#1]
In ROS Kinetic shape_tools has been merged with geometric_shapes. I install this package but i can't compile the moveit_pkgs because i don't have the cmake shape tools files.
What do i have to do?

**Comment by JenniferBuehler** [comment]
Hi,

the packages are not adjusted for Kinetic yet, I hope I'll get around to do this some time soon. You could try to change ``shape_tools`` against ``geometric_tools`` in the CMakeLists.txt and the package.xml, and fix the upcoming compiler errors (if there are any) accordingly.

Or you could just use Jade or Indigo until I fix up the packages for Kinetic.

Jennifer

**Comment by KlasKronander** [comment]
This is a very easy fix, only minor compilation errors related to new namespace (shape_tools => geometric_shapes). I created a kinetic branch here that fixes this. https://github.com/KlasKronander/moveit-pkgs/tree/kinetic

**Comment by JenniferBuehler** [comment]
Hi, thanks for sharing this! Hopefully I'll get around soon to update all my packages to Kinetic.

**Comment by liadbiz** [comment]
Hi,  @JenniferBuehler , Same problem here.
I repalce `shape_tools` to `geometric_tools` in the  CMakeLists.txt and the package.xml, but there are so many compiling errors that I don't known how to solve, So have you fixe it for Kinetic?

Sorry I don't know how to store error information into a file now....I will post here if I can..

**Comment by JenniferBuehler** [comment]
Hi, I will try to do the kinetic branch this weekend.

**Comment by JenniferBuehler** [comment]
Sorry this got completely under the radar. Not sure if this is still relevant for you, but there is now a ``kinetic`` branch which you can use. It will be in the master branch soon, after everything is tested again. I'm closing this now, if you have any more issues with this, please re-open this.

**Comment by JenniferBuehler** [comment]
Update: it's actually already on master now, I've made an ``indigo`` branch instead for the old code.
